export enum ExpenseCategoryEnum {
  BILLS = "bills",
  CLOTHING = "clothing",
  ELECTRONICS = "electronics",
  HOME_APPLIANCES = "home_appliances",
  FASHION = "fashion",
  GROCERY = "grocery",
  GROCERY_PERSONAL = "grocery_personal",
  ENTERTAINMENT = "entertainment",
  TRANSPORTATION = "transportation",
  DINING_OUT = "dining_out",
  HEALTHCARE = "healthcare",
  EDUCATION = "education",
  INSURANCE = "insurance",
  SAVINGS_INVESTMENTS = "savings_investments",
  SUBSCRIPTIONS = "subscriptions",
  LOANS_DEBTS = "loans_debts",
  CHARITY_DONATIONS = "donations",
  PETS = "pets",
  PERSONAL_CARE = "personal_care",
  TRAVEL = "travel",
  GIFTS = "gifts",
  TAXES = "taxes",
}
