apiVersion: apps/v1
kind: Deployment
metadata:
  name: et-frontend-deployment
  labels:
    app: et-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: et-frontend
  template:
    metadata:
      labels:
        app: et-frontend
    spec:
      containers:
        - name: et-frontend
          image: divyankshah09/et-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_BACKEND_URL
              value: http://localhost:8000
