export const ReactQueryNames = {
  LOGIN: "login",
  SIGNUP: "signup",
  FORGOT_PASSWORD: "forgot_password",
  ADD_INCOME: "add_income",
  UPDATE_INCOME: "update_income",
  ADD_EXPENSE: "add_expense",
  UPDATE_EXPENSE: "update_expense",
  ADD_RECURRING_EXPENSE: "add_recurring_expense",
  GET_INCOME: "get_income",
  GET_INCOME_BY_USERID: "get_income_by_userid",
  GET_INCOME_BY_YEAR: "get_income_by_year",
  GET_EXPENSE: "get_expense",
  GET_EXPENSE_BY_USERID: "get_expense_by_userid",
  GET_EXPENSE_BY_YEAR: "get_expense_by_year",
  GET_EXPENSE_BY_MONTH_CATEGORY: "get_expense_by_month_category",
};
